### ISSUE TITLE
Json parsing for free

### ISSUE THREAD

**Issue by aomalov** [VATBox/Epoximise#1]
I would appreciate the protected members from EpoximiseBuilder to become public

**Comment by talgendler** [comment]
@aomalov which ones?

**Comment by aomalov** [comment]
[These right here: ](https://github.com/VATBox/Epoximise/blob/master/src/main/scala/com/vatbox/epoximise/Epoximise.scala#L67)

**Comment by talgendler** [comment]
@aomalov are you talking about:
```scala
override protected val parser: EpoximiseParser
override protected val serializer: EpoximiseSerializer
```

Why ?

**Comment by aomalov** [comment]
Someone would love to use the parser on his own - and cannot access it

**Comment by talgendler** [comment]
@aomalov I don't think this is the case. If someone will want to customize this then it should extend Epoximise trait.

**Comment by aomalov** [comment]
I use the parser- so I instantiate it on my own - I thought I could use the one that comes for free with the epox builder
